/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-01 16:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>main</title>\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/main.css?ver=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/top10.css?ver=2\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"play_listBox\">\r\n");
      out.write("        <div class=\"container mt-3\">\r\n");
      out.write("            <h4>이어지는 노래</h4>\r\n");
      out.write("            <div id=\"play_list\" class=\"card-body\">\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"imgBox\"><img src=\"img/music.png\" alt=\"\"></div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div>노재제목</div>\r\n");
      out.write("                            <div>가수</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button id=\"delete_btn\" type=\"button\" class=\"btn\"><i class=\"fa-regular fa-trash-can\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div class=\"imgBox\"><img src=\"img/music.png\" alt=\"\"></div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div>노재제목</div>\r\n");
      out.write("                            <div>가수</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button id=\"delete_btn\" type=\"button\" class=\"btn\"><i class=\"fa-regular fa-trash-can\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"title_search\" class=\"row\">\r\n");
      out.write("        <h4 class=\"col\"><a href=\"main.jsp\">DD Music</a></h4>\r\n");
      out.write("        <div class=\"col-1\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <div class=\"card-body nav-w\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-3\"><i class=\"fa-solid fa-user\"></i></div>\r\n");
      out.write("                    <div class=\"col-6\">사용자 <i class=\"fa-solid fa-caret-down\"></i></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list-group my-group\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"list-group-item list-group-item-light\"><a href=\"\">My 멤버십</a></li>\r\n");
      out.write("                        <li class=\"list-group-item list-group-item-light\"><a href=\"\">공지사항</a></li>\r\n");
      out.write("                        <li class=\"list-group-item list-group-item-light\"><a href=\"\">로그인</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"\">투데이</a></li>\r\n");
      out.write("                    <li><a href=\"http://127.0.0.1:5000/\">차트</a></li>\r\n");
      out.write("                    <li><a href=\"\">최신앨범</a></li>\r\n");
      out.write("                    <li><a href=\"\">DJ 스테이션</a></li>\r\n");
      out.write("                    <li><a href=\"\">MAG</a></li>\r\n");
      out.write("                    <li><a href=\"\">이달의 노래</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <div>보관함</div>\r\n");
      out.write("                    <li><a href=\"\">믹스테잎</a></li>\r\n");
      out.write("                    <li><a href=\"\">노래</a></li>\r\n");
      out.write("                    <li><a href=\"\">아티스트</a></li>\r\n");
      out.write("                    <li><a href=\"\">앨범</a></li>\r\n");
      out.write("                    <li><a href=\"\">플레이리스트</a></li>\r\n");
      out.write("                    <li><a href=\"\">받은노래</a></li>\r\n");
      out.write("                    <li><a href=\"\">구매한 MP3</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a>#내돈내듣</a></li>\r\n");
      out.write("                    <li><a href=\"\">ONSTAGE</a></li>\r\n");
      out.write("                    <li><a href=\"\">서비스 소개</a></li>\r\n");
      out.write("                    <li><a href=\"\">맴버십 구독</a></li>\r\n");
      out.write("                    <li><a href=\"\">사용자 리뷰</a></li>\r\n");
      out.write("                    <li><a href=\"\">커밍쑨</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a>#내돈내듣</a></li>\r\n");
      out.write("                    <li><a href=\"\">ONSTAGE</a></li>\r\n");
      out.write("                    <li><a href=\"\">서비스 소개</a></li>\r\n");
      out.write("                    <li><a href=\"\">맴버십 구독</a></li>\r\n");
      out.write("                    <li><a href=\"\">사용자 리뷰</a></li>\r\n");
      out.write("                    <li><a href=\"\">커밍쑨</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div id=\"srch_bar\">\r\n");
      out.write("            <form class=\"form-inline\" action=\"\">\r\n");
      out.write("                <input class=\"form-control mr-2 col\" type=\"text\" id=\"\" name=\"\" placeholder=\"DD Music 검색\" autofocus>\r\n");
      out.write("                <button class=\"btn btn-secondary col-1\" type=\"submit\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <video style=\"width: 100%;\" src=\"\" autoplay muted></video>\r\n");
      out.write("    </header>\r\n");
      out.write("    <section>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-row-box\">\r\n");
      out.write("                <div class=\"section-row\">\r\n");
      out.write("                    <h5><a href=\"\">매거진 > </a></h5>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\"\r\n");
      out.write("                                    src=\"https://music-phinf.pstatic.net/20211028_79/1635391214685dCLaq_JPEG/1.jpeg?type=w720\"\r\n");
      out.write("                                    alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">이주의 디깅 #121 아델</a>\r\n");
      out.write("                            <div>2021.10.26</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/a1.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">New Release #64 : 디제이 스네이크, 홍광호</a>\r\n");
      out.write("                            <div>2021.10.25</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/a2.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">꼭 들어야 할 여섯 장의 앨범 : 따마, 데드보이즈</a>\r\n");
      out.write("                            <div>2021.10.22</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/11..png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">이주의 디깅 #120 스트릿 우먼 파이터</a>\r\n");
      out.write("                            <div>2021.10.19</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/12.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">New Release #63 : 아델 , 스텔라 장</a>\r\n");
      out.write("                            <div>2021.10.18</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/13.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">무엇이든 물어보세요 : 트라이비(TRI.BE)</a>\r\n");
      out.write("                            <div>2021.10.14</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"section-row-box\">\r\n");
      out.write("                <div class=\"section-row\">\r\n");
      out.write("                    <h5><a href=\"\">NEWS > </a></h5>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/1.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">아델의 Easy on Me가 '빌보드 핫 100' 1위를 차지하였습니다</a>\r\n");
      out.write("                            <div>관련 뉴스 보기</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/2.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">라잇썸의 'VAVACE'가 빌보드 월드 디지털 송 차트에서 8위를 차지하였습니다</a>\r\n");
      out.write("                            <div>관련 뉴스 보기</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/3.jpg\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">온앤오프가 첫 단독 콘서트를 개최합니다</a>\r\n");
      out.write("                            <div>관련 뉴스 보기</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <dia href=\"\" v class=\"section-img-box\"><img class=\"section-img\" src=\"img/4.png\" alt=\"\">\r\n");
      out.write("                            </dia>\r\n");
      out.write("                            <a href=\"\">자우림이 단독 콘서트 '영원한 사랑'을 개최 합니다</a>\r\n");
      out.write("                            <div>관련 뉴스 보기</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/5.jpg\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">이달의 소녀가 오리콘 데일리 차트 3위에 올랐습니다</a>\r\n");
      out.write("                            <div>관련 뉴스 보기</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <a href=\"\" class=\"section-img-box\"><img class=\"section-img\" src=\"img/6.png\" alt=\"\"></a>\r\n");
      out.write("                            <a href=\"\">황치열이 2년 만에 단독 콘서트를 개최합니다</a>\r\n");
      out.write("                            <div>관련 뉴스 보기</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h2 class=\"mb-5\">DD Music Top 10</h2>\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/40662/4066238.jpg?version=20211020063535.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">strawberry moon</div>\r\n");
      out.write("                            <div name=\"top10Artist\">아이유(IU)</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/204243/20424398.jpg?version=20211015010640.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">Savage</div>\r\n");
      out.write("                            <div name=\"top10Artist\">aespa</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>3</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/204256/20425653.jpg?version=20211020003234.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">Upper Side Dreamin’</div>\r\n");
      out.write("                            <div name=\"top10Artist\">ENHYPEN</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>4</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/40666/4066688.jpg?version=20211030065545.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">낮 밤 (feat. 박재범)</div>\r\n");
      out.write("                            <div name=\"top10Artist\">이영지</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>5</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/40665/4066507.jpg?version=20211027003705.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">나비효과</div>\r\n");
      out.write("                            <div name=\"top10Artist\">볼빨간사춘기</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>6</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/204256/20425653.jpg?version=20211020003234.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">Attention, please!</div>\r\n");
      out.write("                            <div name=\"top10Artist\">ENHYPEN</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>7</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/40665/4066507.jpg?version=20211027003705.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">너는 내 세상이었어</div>\r\n");
      out.write("                            <div name=\"top10Artist\">볼빨간사춘기</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>8</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/204256/20425653.jpg?version=20211020003234.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">모 아니면 도 (Go Big or Go Home)</div>\r\n");
      out.write("                            <div name=\"top10Artist\">ENHYPEN</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>9</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/204282/20428261.jpg?version=20211027010045.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">Favorite (Vampire)</div>\r\n");
      out.write("                            <div name=\"top10Artist\">NCT</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td><div class=\"imgBox\"><img src=\"https://image.bugsm.co.kr/album/images/50/40667/4066711.jpg?version=20211030065544.0\" alt=\"\"></div></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div name=\"top10Title\">XOXO</div>\r\n");
      out.write("                            <div name=\"top10Artist\">전소미</div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><button name=\"add_btn\" type=\"button\" class=\"btn\"><i class=\"fas fa-plus\"></i></button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <p>주소 : 충청북도 청주시 서원구 사직대로 109 그린컴퓨터아트</p>\r\n");
      out.write("            <p>이메일 : power6120@naver.com</p>\r\n");
      out.write("            <p>Copyright ⓒ 2021. DoubleD. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <input id=\"play_bar\" type=\"range\" value=\"0\">\r\n");
      out.write("        <div class=\"d-flex ml-4\">\r\n");
      out.write("            <div class=\"pt-3\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div id=\"controls_imgBox\" class=\"imgBox\"><img src=\"img/music.png\" alt=\"\"></div>\r\n");
      out.write("                    <div class=\"controls-song ml-2\">\r\n");
      out.write("                        <div id=\"controls_title\">노래제목</div>\r\n");
      out.write("                        <div id=\"controls_artist\">가수</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ml-3 mt-3\">\r\n");
      out.write("                <button class=\"btn\" type=\"button\"><i class=\"fa-regular fa-heart\"></i></button>\r\n");
      out.write("                <button style=\"display: none;\" class=\"btn\" type=\"button\"><i class=\"fa-solid fa-heart\"></i></button>\r\n");
      out.write("                <button class=\"btn\" type=\"button\"><i class=\"fa-solid fa-music\"></i></button>\r\n");
      out.write("                <button class=\"btn\" type=\"button\"><i class=\"fa-solid fa-ellipsis\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ml-auto mr-auto mt-2\">\r\n");
      out.write("                <button id=\"suffle_btn\" class=\"btn\" type=\"button\" title=\"재생 방법 변경\"><i\r\n");
      out.write("                        class=\"fa-solid fa-shuffle\"></i></button>\r\n");
      out.write("                <button id=\"back_btn\" class=\"btn\" type=\"button\"><i class=\"fa-solid fa-backward-step fa-2x\"></i></button>\r\n");
      out.write("                <button id=\"play_btn\" class=\"btn\" type=\"button\" title=\"재생/일시정지 선택\"><i\r\n");
      out.write("                        class=\"fa-regular fa-circle-play fa-3x\"></i></button>\r\n");
      out.write("                <button id=\"pause_btn\" style=\"display: none;\" class=\"btn\" type=\"button\"><i\r\n");
      out.write("                        class=\"fa-regular fa-circle-pause fa-3x\"></i></button>\r\n");
      out.write("                <button id=\"next_btn\" class=\"btn\" type=\"button\"><i class=\"fa-solid fa-forward-step fa-2x\"></i></button>\r\n");
      out.write("                <button id=\"repeat_btn\" class=\"btn\" type=\"button\" title=\"반복 재생 설정\"><i\r\n");
      out.write("                        class=\"fa-solid fa-repeat\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ml-auto d-flex mt-4\">\r\n");
      out.write("                <div id=\"controls_time\" class=\"mt-2\">00:00 / 00:00</div>\r\n");
      out.write("                <div id=\"mute_btn1\" class=\"ml-2\"><button class=\"btn\" type=\"button\"><i\r\n");
      out.write("                            class=\"fa-solid fa-volume-high\"></i></button></div>\r\n");
      out.write("                <div id=\"mute_btn2\" class=\"ml-2\" style=\"display: none;\"><button class=\"btn\" type=\"button\"><i\r\n");
      out.write("                            class=\"fa-solid fa-volume-xmark\"></i></button></div>\r\n");
      out.write("                <div class=\"ml-1 mt-1\"><input id=\"volume_bar\" type=\"range\" min=\"0\" max=\"100\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ml-3 pt-3 mr-3\">\r\n");
      out.write("                <button id=\"playlistUp_btn\" class=\"btn\" type=\"button\"><i class=\"fa-solid fa-arrow-down-short-wide fa-2x fa-flip-vertical\"></i></button>\r\n");
      out.write("                <button style=\"display: none;\" id=\"playlistDown_btn\" class=\"btn\" type=\"button\"><i class=\"fa-solid fa-arrow-down-wide-short fa-2x\"></i></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <audio id=\"player\" src=\"\"></audio>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("        integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"js/main.js?ver=1\"></script>\r\n");
      out.write("    <script src=\"js/player.js?ver=2\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
